### ISSUE TITLE
Proposal api

### ISSUE THREAD

**Issue by JBlaak** [DJWassink/Promise-parallel-throttle#1]
Current api does not allow full control on how the promises are generated, it "magically" inserts the parameters of the passed function, might be better to have a list of functions to be executed, e.g.:

```javascript
const doReq = async (firstName, lastName) => {
    return ...//something async
}

const users = [
    { first_name: 'Joris', last_name: 'Blaak'},
    { first_name: 'Dirk-Jan', last_name: 'Wassink'}
];

const queue = users.map(user => {
    return () => doReq(user.first_name, user.last_name);
});

ParallelPromiseThrottle(queue);
```

**Comment by JBlaak** [comment]
@DJWassink since your slogan says `It's like Promise.all(), but throttled!`, why not have a similar api?

`Throttle.all(queue)` defaults to some kind of default parallel behavior (5 simultaneous or something) 
`Throttle.parallel(5, queue)` runs the queue with 5 in parallel
`Throttle.sync(queue)` runs `Throttle.parallel(1, queue)`
etc.

This allows for extending the api and using the lib without learning any new stuff

**Comment by JBlaak** [comment]
You can then use same behavior as `Promise.all`, without the custom object.

**Comment by DJWassink** [comment]
WIP in https://github.com/DJWassink/Promise-parallel-throttle/tree/change/simpeler-api
