### ISSUE TITLE
Resolve immediately if tasks array is empty

### ISSUE THREAD

**Issue by travellingprog** [DJWassink/Promise-parallel-throttle#11]
Right now, if the tasks array is empty, then `Throttle.all()` will just hang. `Promise.all()` would resolve instead. I can get past this in my code easily enough, but for compatibility with Promise.all(), it should have the same behaviour.

**Comment by DJWassink** [comment]
Good catch will fix this this evening. Thnx!

**Comment by DJWassink** [comment]
Fixed in v2.3.0

Cheers!
