### ISSUE TITLE
Remove es6-promise from declaration file

### ISSUE THREAD

**Issue by monolithed** [DJWassink/Promise-parallel-throttle#17]
The reason why I'm asking for is:

```js
node_modules/promise-parallel-throttle/build/throttle.d.ts(1,1): error TS2688: Cannot find type definition file for 'es6-promise'.
```

**Comment by DJWassink** [comment]
Could you try version 2.3.1? I removed the @types/es6-promise in favor of settings the lib compiler option in the tsconfig

**Comment by monolithed** [comment]
That works fine, but only with my PR https://github.com/DJWassink/Promise-parallel-throttle/pull/16

![img-2017-04-28-17-51-40](https://cloud.githubusercontent.com/assets/803674/25534108/79508416-2c3b-11e7-83ea-caab9e2411a1.png)

**Comment by monolithed** [comment]
Without my PR:

```ts
declare module 'promise-parallel-throttle' {
	import * as promise from 'promise-parallel-throttle/build/throttle';

	export = promise;
}
```
