### ISSUE TITLE
Throttle.all not compatible with Promise.all

### ISSUE THREAD

**Issue by TobiaszCudnik** [DJWassink/Promise-parallel-throttle#29]
`Throttle.all` accepts a list of functions, where `Promise.all` accepts a list of `Promise` instances.

Reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

**Comment by DJWassink** [comment]
Hey, thanks for using this library.

To keep it short, we have to wrap every promise in a function which (when executed) will trigger the promise, else there is no possibility to throttle the promises.

That's also why the slogan says `it's kinda like Promise.all()` 😉 

Anyhow for a longer explanation check this comment: https://github.com/DJWassink/Promise-parallel-throttle/issues/25#issuecomment-414271876

Hope this helps.

**Comment by TobiaszCudnik** [comment]
Sorry I brain farted, once you start a promise you cant throttle it, so the API cant be identical.
