### ISSUE TITLE
No support for node v18.18.2 anymore?

### ISSUE THREAD

**Issue by mateustome** [DJWassink/Promise-parallel-throttle#40]
I'm having this issue when installing another package that have ppt as dependency. 
error promise-parallel-throttle@3.4.0: The engine "node" is incompatible with this module. Expected version ">=20.11.0". Got "18.18.2"

**Comment by DJWassink** [comment]
Ooh wow.

Thats a mistake on my end. 
Let me push a new version without that restriction!

**Comment by DJWassink** [comment]
Please try version 3.4.1 it should have been fixed :)

**Comment by mateustome** [comment]
Thank you very much! Its fixed now 😃
