### ISSUE TITLE
pass task index to `progressCallback`

### ISSUE THREAD

**Issue by manuel3108** [DJWassink/Promise-parallel-throttle#42]
Sometimes it would be useful to pass the index of task that just finished to `progressCallback` so that we can immediately determine the result state and log something to the console in example.

**Comment by DJWassink** [comment]
Released version 3.5.0 which includes a `lastCompletedIndex`, this index is either a errored / succesfull / nextCheckFailed index.

How this is what ur looking for :)

**Comment by manuel3108** [comment]
Works exactly as expected! Thanks :)
